# Annualised Volatilities Report
> Updated volatilities
- toc: true 
- badges: false
- comments: true
- categories: [jupyter]
- image: images/chart-preview.png

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option('display.max_rows', None)    # prevent dfs from being truncated

In [2]:
## IMPORT DATA ##
data_path = Path("C:/Users/SamCurtis/AppData/Local/bipy/28095931/projects/02f1bf62483a4d82b93898b71672e018") / ("tableau_vols.xlsx")
raw_baseload = pd.read_excel(data_path, sheet_name='Baseload')
raw_caps = pd.read_excel(data_path, sheet_name='Caps')
raw_strips = pd.read_excel(data_path, sheet_name='Strips')


last_update_path = Path("C:/Users/SamCurtis/AppData/Local/bipy/28095931/projects/02f1bf62483a4d82b93898b71672e018") / ("volatility_data.xlsx")
last_updated = pd.read_excel(last_update_path, sheet_name='last_updated')
last_updated = last_updated['updated'][0]

In [3]:
print('Last Updated: ', last_updated)

Last Updated:  2021-06-02 10:17:53

## Baseload Contracts

In [4]:
baseload_pivot = pd.pivot_table(raw_baseload, index=["state", "year","quater"])
baseload_pivot = baseload_pivot.iloc[:,1:]
baseload_pivot

                   annual  monthly   qtrly  weekly
state year quater
NSW   2021 2       0.3183   0.8198  0.5456  1.1557
           3       0.2027   0.2730  0.2393  0.4931
           4       0.2031   0.2931  0.2383  0.5390
      2022 1       0.1910   0.1395  0.2442  0.1913
           2       0.1696   0.1625  0.1858  0.2873
           3       0.1550   0.1443  0.1554  0.1748
           4       0.1610   0.1386  0.1907  0.1788
      2023 1       0.1682   0.1533  0.2263  0.1889
           2       0.1825   0.1240  0.1727  0.2014
           3       0.1821   0.1216  0.1741  0.2046
           4       0.1628   0.1185  0.1684  0.1964
      2024 1          NaN   0.1190  0.1811  0.2159
           2          NaN   0.0760  0.1421  0.0864
           3          NaN   0.0951  0.0808  0.1025
           4          NaN   0.0836  0.0733  0.0000
      2025 1          NaN   0.1755     NaN  0.0000
           2          NaN   0.0755     NaN  0.0000
QLD   2021 2       0.3681   0.9547  0.6287  1.6844
           3       0.2559   0.5563  0.3685  1.1535
           4       0.2049   0.2464  0.2189  0.4479
      2022 1       0.1757   0.2321  0.2225  0.4185
           2       0.1759   0.2587  0.2314  0.3733
           3       0.1616   0.1990  0.1857  0.3736
           4       0.1687   0.2145  0.2094  0.3741
      2023 1       0.1592   0.1551  0.2080  0.3132
           2       0.1689   0.1503  0.1905  0.2900
           3       0.1611   0.1717  0.1885  0.3561
           4       0.2141   0.1615  0.2115  0.3364
      2024 1          NaN   0.0730  0.1511  0.0668
           2          NaN   0.0926  0.1358  0.0664
           3          NaN   0.1453  0.1542  0.0000
           4          NaN   0.1375  0.1635  0.0000
      2025 1          NaN   0.7137     NaN  0.0000
           2          NaN   0.0967     NaN  0.0000
SA    2021 2       0.2868   0.6359  0.4615  0.5045
           3       0.1774   0.2604  0.2225  0.3580
           4       0.1687   0.1144  0.1699  0.0393
      2022 1       0.2041   0.2044  0.2414  0.0887
           2       0.1694   0.1640  0.1992  0.0409
           3       0.1783   0.1409  0.1692  0.0275
           4       0.1671   0.1369  0.1603  0.0272
      2023 1       0.2025   0.2121  0.2790  0.0267
           2       0.2911   0.5186  0.3824  0.0266
           3       0.3108   0.5055  0.3492  0.1909
           4       0.2331   0.0927  0.1891  0.1902
      2024 1          NaN   0.1718  0.1970  0.1203
           2          NaN   0.4251  0.3597  0.3022
           3          NaN   0.0453  0.1538  0.0000
           4          NaN   0.0452  0.2772  0.0000
      2025 1          NaN   0.0984     NaN  0.0000
           2          NaN   0.0452     NaN  0.0000
VIC   2021 2       0.3640   0.8184  0.6185  0.6376
           3       0.2292   0.2483  0.2837  0.2750
           4       0.2322   0.1962  0.2737  0.2476
      2022 1       0.2428   0.1530  0.3023  0.1672
           2       0.2393   0.2176  0.3344  0.2557
           3       0.2258   0.2037  0.3022  0.2587
           4       0.2484   0.1444  0.3734  0.1166
      2023 1       0.1967   0.1257  0.2785  0.1531
           2       0.1696   0.1200  0.2297  0.1608
           3       0.1896   0.1204  0.2477  0.1240
           4       0.1906   0.1195  0.2871  0.1420
      2024 1          NaN   0.1194  0.2599  0.0785
           2          NaN   0.1545  0.1955  0.1322
           3          NaN   0.2719  0.2556  0.0631
           4          NaN   0.2434  0.2265  0.0353
      2025 1          NaN   0.3814     NaN  0.0000
           2          NaN   0.2371     NaN  0.0000

## Caps

In [5]:
cap_pivot = pd.pivot_table(raw_caps, index=["state", "year","quater"])
cap_pivot = cap_pivot.iloc[:,1:]
cap_pivot

                   annual  monthly   qtrly  weekly
state year quater
NSW   2021 2       1.2677   3.8731  2.4494  2.8816
           3          NaN   1.1141  0.7400  1.0492
           4          NaN   0.4597     NaN  0.4935
      2022 1          NaN   0.4091     NaN  0.3786
           2          NaN   0.4670     NaN  0.7364
           3          NaN   0.5760     NaN  1.0268
           4          NaN   0.3976     NaN  0.7590
      2023 1          NaN   0.3853     NaN  0.5166
           2          NaN   0.3855     NaN  0.7497
           3          NaN   0.3324     NaN  0.3078
           4          NaN   0.0378     NaN  0.0000
      2024 1          NaN   0.3531     NaN  0.0867
           2          NaN   0.0000     NaN  0.0000
           3          NaN   0.0000     NaN  0.0000
           4          NaN   0.0000     NaN  0.0000
      2025 1          NaN   2.3025     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000
QLD   2021 2       1.2292   3.0893  2.2779  5.1332
           3          NaN   2.0386  1.3246  3.7988
           4          NaN   0.4006     NaN  0.2846
      2022 1          NaN   0.7663     NaN  1.5186
           2          NaN   0.5826     NaN  1.0311
           3          NaN   1.6447     NaN  3.6043
           4          NaN   0.3832     NaN  0.6781
      2023 1          NaN   0.5909     NaN  0.2813
           2          NaN   0.3902     NaN  0.4599
           3          NaN   0.3902     NaN  0.4599
           4          NaN   0.3919     NaN  0.2803
      2024 1          NaN   0.5796     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000
           3          NaN   0.0000     NaN  0.0000
           4          NaN   0.0000     NaN  0.0000
      2025 1          NaN   0.0000     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000
SA    2021 2       1.0620   3.4077  2.0807  0.8059
           3          NaN   0.6955  0.6889  0.0000
           4          NaN   0.8202     NaN  0.0000
      2022 1          NaN   0.4253     NaN  0.0000
           2          NaN   0.7376     NaN  0.6322
           3          NaN   0.6142     NaN  0.0000
           4          NaN   0.5910     NaN  0.1892
      2023 1          NaN   0.3054     NaN  0.1165
           2          NaN   0.3844     NaN  0.4446
           3          NaN   0.3844     NaN  0.4446
           4          NaN   0.2357     NaN  0.4446
      2024 1          NaN   0.2735     NaN  0.1165
           2          NaN   0.4974     NaN  0.9249
           3          NaN   0.4974     NaN  0.9249
           4          NaN   0.1982     NaN  0.4172
      2025 1          NaN   0.3231     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000
VIC   2021 2       1.5429   5.0785  3.0535  1.2225
           3          NaN   1.5175  1.0261  0.6760
           4          NaN   0.3633     NaN  0.0000
      2022 1          NaN   0.3302     NaN  0.1681
           2          NaN   0.7957     NaN  0.2488
           3          NaN   0.5942     NaN  0.0690
           4          NaN   0.2390     NaN  0.0707
      2023 1          NaN   0.2669     NaN  0.0000
           2          NaN   0.5916     NaN  0.0000
           3          NaN   0.3004     NaN  0.0000
           4          NaN   0.0000     NaN  0.0000
      2024 1          NaN   0.0000     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000
           3          NaN   0.0000     NaN  0.0000
           4          NaN   0.0000     NaN  0.0000
      2025 1          NaN   0.0000     NaN  0.0000
           2          NaN   0.0000     NaN  0.0000

## Strips

In [6]:
strips_pivot = pd.pivot_table(raw_strips, index=["state", "year","prod_type"])
strips_pivot = strips_pivot.iloc[:,1:]
strips_pivot

                      annual  monthly   qtrly  quater  weekly
state year prod_type
NSW   2022 Cal        0.1463   0.1260  0.1699       4  0.1924
           Fin        0.1703   0.2046  0.2056       2  0.3638
      2023 Cal        0.1523   0.1217  0.1658       4  0.1918
           Fin        0.1360   0.1279  0.1653       2  0.1774
      2024 Cal           NaN   0.0741  0.0973       4  0.1028
           Fin           NaN   0.0870  0.1390       2  0.1214
      2025 Fin           NaN   0.0862     NaN       2  0.0248
QLD   2022 Cal        0.1541   0.2138  0.1997       4  0.3788
           Fin        0.1807   0.3001  0.2384       2  0.5839
      2023 Cal        0.1570   0.1554  0.1926       4  0.3159
           Fin        0.1438   0.1367  0.1777       2  0.2404
      2024 Cal           NaN   0.1048  0.1402       4  0.0356
           Fin           NaN   0.0841  0.1412       2  0.1357
SA    2022 Cal        0.1464   0.1455  0.1733       4  0.0426
           Fin        0.1393   0.1374  0.1679       2  0.0893
      2023 Cal        0.2139   0.2260  0.2356       4  0.0996
           Fin        0.1530   0.1452  0.1925       2  0.0274
      2024 Cal           NaN   0.1023  0.2016       4  0.1041
           Fin           NaN   0.2115  0.2188       2  0.1907
      2025 Fin           NaN   0.0499     NaN       2  0.0000
VIC   2022 Cal        0.2050   0.1535  0.2802       4  0.1907
           Fin        0.2123   0.1784  0.2734       2  0.2058
      2023 Cal        0.1635   0.1090  0.2421       4  0.1391
           Fin        0.1666   0.1233  0.2379       2  0.1619
      2024 Cal           NaN   0.1540  0.2027       4  0.0640
           Fin           NaN   0.1134  0.2104       2  0.0758
      2025 Fin           NaN   0.2690     NaN       2  0.0207